### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by jakepurple13** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#1]
When I was putting the line
`compile 'com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0'`
into the gradle, Android Studio was yelling at me
`Error:(44, 13) Failed to resolve: com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0`

**Comment by myinnos** [comment]
**Make sure add maven to repositories**
- **_Check Internet connection as well_** 

In build.gradle (Project)
```
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
```
And then in the other gradle file(may be your app gradle or your own module library gradle, but never add in both of them to avoid conflict.)
```
dependencies {
        compile 'com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0'
        }
```

**Comment by jakepurple13** [comment]
Well don't I feel stupid now. It worked right away. Thanks!

**Comment by myinnos** [comment]
**Happy Coding 👍 **
