### ISSUE TITLE
Showing or Hiding the fast scroll

### ISSUE THREAD

**Issue by srikanthkancheti** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#12]
Hi, I want to hide the Fast scroll when user filtering the recycle view and I want to make the Fast scroll visible if the search edit text length is zero. Help me on showing and hiding the Fast scroll.

**Comment by myinnos** [comment]
you can use this feature to show/hide IndexBar
` mRecyclerView.setIndexBarVisibility(true);`

This function available from version [1.0.5](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/releases/tag/1.0.5)
