### ISSUE TITLE
crash when list size zero and click on index bar

### ISSUE THREAD

**Issue by DashrathAhir** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#13]
When list size zero and click on index bar crash app even hide the index bar and set width 0

**Comment by myinnos** [comment]
add this line in your code.

```
if(mDataArray.size() == 0 || mDataArray == null){
         mRecyclerView.setIndexBarVisibility(false);
}
```

**if list data null/empty index bar will hide.**

**Comment by myinnos** [comment]
Fixed this, Please upgrade to latest version([1.0.6](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/releases/tag/1.0.6))

```
dependencies {
   compile 'com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.6'
}
```
