### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by MFlisar** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#15]
I would have following suggestions:

* change your color attributes to be integers instead of strings
* remove the transparency parameter => just extract the transparency from the color itself

This breaks your current API though but would fit to the way nearly every android library works. I would add this to my pull request if that's ok for you

**Comment by appspell** [comment]
implemented here https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/pull/29

**Comment by valonsejdini** [comment]
Can we add # symbol as a first/last position in the alphabet indexer ?

**Comment by MFlisar** [comment]
Thanks. I just checked the code - if the user provides a `indexbarBackgroudAlpha` AND a `indexbarBackgroudColor` with an alpha value != 255, those 2 alphas will both be applied, correct? I think this may be a bit confusing, but other than this, thanks.

I personally would remove the alpha as attribute at all - it should always be part of the color itself and extracted from the color value itself. Just a suggestion though of course

**Comment by myinnos** [comment]
Yes @MFlisar 
Thanks for your suggestion, Sure I will add this in future.
