### ISSUE TITLE
getSections() should be called if adapter calls notifyDataSetChanged()

### ISSUE THREAD

**Issue by siralam** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#19]
Normally we set adapter in recyclerview first before we downloaded all items from internet, and set the list later on which at the same time calls notifyDataSetChanged().

But I found that the indexBar doesn't update accordingly. In fact since this is the case, the "sectionPositions" arraylist always remains empty.

**Comment by myinnos** [comment]
Your right,
Currently this Lib is act like as you said, Basically if there is no data or User playing with views(VISIBLE/INVISIBLE) we dont need to append the adapter to recycler.
Incase if you feel that any right process, please fork the repo and pull the request. i will update your code with current Lib.
Thank you.
