### ISSUE TITLE
Quick question about color change

### ISSUE THREAD

**Issue by jakepurple13** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#2]
So currently I'm working on getting themes to change. Wanna throw something out the window.

Is there anyway to change the color of the text on the scroller? Is there also a way to call from colors.xml to change the color?

**Comment by myinnos** [comment]
Note: this function not available in previous version`(1.0)`, to use this function upgrade [AlphabetIndex Fast Scroll RecyclerView](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView)  to latest version`(1.0.1)`
```
dependencies {
   compile 'com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.1'
}
```

- Change IndexBarTextColor:
```java
 mRecyclerView.setIndexBarTextColor("#FFFFFF");
```

**Comment by jakepurple13** [comment]
Awesome! Thanks so much! I had a small issue which I did a quick search on StackOverflow to fix and it was calling a color resource in. It didn't really work. I ended up finding this:
`"#"+Integer.toHexString(getResources().getColor(R.color.redish))`
And that seemed to do the trick.

**Comment by myinnos** [comment]
You just pass as a `string`! 

Any way this is also good solution `"#"+Integer.toHexString(getResources().getColor(R.color.redish))`

Am closing this issue! if you still need help on same issue you can `reopen` this! or `Open New Issue`

**Comment by xuanthupro** [comment]
Hi,
I can not set full transparent color for the scroll bar
I used:
recyclerView.setIndexBarTransparentValue(0f);
recyclerView.setIndexBarColor("#00000000");

But neither of them work.
Can you help me?

Thanks
