### ISSUE TITLE
Failed to resolve: com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.9

### ISSUE THREAD

**Issue by karishmapujara** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#20]
Hello
I am getting this error when I sync gradle file
**Failed to resolve: com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.9**

**Comment by myinnos** [comment]
**Kindly use the following links to use this library:**

In build.gradle (Project)

```
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
```
And then in the other gradle file(may be your app gradle or your own module library gradle, but never add in both of them to avoid conflict.)

```
dependencies {
    compile 'com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.9'
}
```

**Comment by karishmapujara** [comment]
Hello sir
Still receiving the error while syncing version 1.0.9.
But in version 1.0.8, there is no error.

**Comment by myinnos** [comment]
Thanks for the **info**, I will take a look at this!

**Comment by myinnos** [comment]
Please post here stack trace of error ?

**Comment by karishmapujara** [comment]
Here is the error I see in Messages Tab.

![error](https://user-images.githubusercontent.com/3817026/29824974-94229c50-8cf0-11e7-8c06-864cecb0978f.PNG)

**Comment by tunacoder** [comment]
shit

**Comment by tunacoder** [comment]
1.0.8 & 1.0.9 both not working

**Comment by bcodermicro** [comment]
Ditto 1.0.8 and 1.0.9 not working...any ideas?

**Comment by mikemilla** [comment]
`1.0.92` works for me. `1.0.94` is broken cc: @myinnos 

You may also want to update the docs with gradle `implementation` syntax instead of `compile`

**Comment by myinnos** [comment]
@mikemilla done 👍

**Comment by ghost** [comment]
@myinnos v1.0.94 is still broken. Can you fix that?

**Comment by theoklink** [comment]
June 2019
@myinnos v1.0.94 is still broken. Can you fix that?

**Comment by AGL-dev** [comment]
@myinnos v1.0.94 is still broken. Can you fix that?
