### ISSUE TITLE
Sometimes the bar is empty

### ISSUE THREAD

**Issue by MFlisar** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#23]
I have an app that is constantly running and showing/hiding it's view on demand (a sidebar like app).

What I see is that rarely the fast scroller shows up empty after some time (after many days, hardly reproduceable).

Any ideas what could cause this? I have no idea yet, did check the fast scrollers code but did not find anything that could cause this..

**Comment by omarmakeen** [comment]
I've the same issue
@MFlisar did you find any solution?

**Comment by MFlisar** [comment]
No. Didn't investigate it further either as it's really rare and I did not find anything.

**Comment by MFlisar** [comment]
I did not see this issue for probably 3/4 year now using my own fork... Created a pull request now with small adjustments, it may have been an issue with the handler hiding the view...

**Comment by myinnos** [comment]
Hello @MFlisar 
Is [this](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/pull/46) pull request solved above issue ?

**Comment by MFlisar** [comment]
It's so long ago so I'm not 100% sure. But my experience with my own fork are that this issue never happened again and checking the difference makes me assume that it had to do with the handler. Using the views handler makes sure, that the runnable is executed correctly...

Not 100% sure anymore, but I'm using your view in a sidebar app that is running all the time on my phone and on my users phone and this issue is gone for a very long time for me

**Comment by myinnos** [comment]
@MFlisar 
Thanks for your contribution i just merged [this](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/pull/46) pull request.

Thank you 👍
