### ISSUE TITLE
Release 1.0.9 and 1.0.91 are not compiled at jitpack

### ISSUE THREAD

**Issue by MFlisar** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#24]
See here:

https://jitpack.io/#myinnos/AlphabetIndex-Fast-Scroll-RecyclerView

Respectively those two logs:
https://jitpack.io/com/github/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/1.0.9/build.log
https://jitpack.io/com/github/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/1.0.91/build.log

**Comment by myinnos** [comment]
Fixed and Released new version
Updated [READ.ME](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/blob/master/README.md)
[1.0.95](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/releases/tag/1.0.95)

Feel free to reopen if issue repeated, Thank you.
