### ISSUE TITLE
setIndexbarMargin doesn't work

### ISSUE THREAD

**Issue by adaerodriguez** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#26]
Hi,

I am with AlphabetIndex-Fast-Scroll-RecyclerView:1.0.8 and I have a problem when I try to remove the margin of the IndexBar. I have tried to set the parameter in the layout and the class but neither work. 

This is how I put in the layout:
Sometimes I could see how the parameter is apply but when I exit and open the layout again, the IndexBar has margin again.

> <in.myinnos.alphabetsindexfastscrollrecycler.IndexFastScrollRecyclerView
>             android:id="@+id/recyclerView"
>             android:layout_width="match_parent"
>             android:layout_height="match_parent"
>             app:setIndexbarMargin="0"  
>             app:setIndexbarWidth="0"
>             />

This is how I put in the class: 

> //Setup recyclerViewFastScroll
> mBinding.incRecyclerView.recyclerView.setIndexBarTransparentValue((float) 1.0);
> mBinding.incRecyclerView.recyclerView.setIndexBarCornerRadius(0);
> mBinding.incRecyclerView.recyclerView.setIndexbarMargin(0);
> mBinding.incRecyclerView.recyclerView.setPreviewPadding(0);
> mBinding.incRecyclerView.recyclerView.setIndexBarColor("#"+Integer.toHexString(ContextCompat.getColor(mActivity, R.color.color_primary_dark)));
> mBinding.incRecyclerView.recyclerView.setIndexbarHighLateTextColor("#"+Integer.toHexString(ContextCompat.getColor(mActivity, R.color.color_eab817)));
>         mBinding.incRecyclerView.recyclerView.setIndexBarHighLateTextVisibility(true);
>         mBinding.incRecyclerView.recyclerView.setIndexBarVisibility(true);

I execute in Android 4.4.2 and Android 6.0.1. 

What's the problem?

**Comment by myinnos** [comment]
Fixed and Released new version
Updated [READ.ME](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/blob/master/README.md)
[1.0.95](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/releases/tag/1.0.95)

Feel free to reopen if issue repeated, Thank you.
