### ISSUE TITLE
misprint in setIndexbarHighLateTextColor

### ISSUE THREAD

**Issue by appspell** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#28]
setIndexbarHighLateTextColor 
I believe,  it should be "Highlight"

**Comment by myinnos** [comment]
Fixed and Released new version
Updated [READ.ME](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/blob/master/README.md)
[1.0.95](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/releases/tag/1.0.95)

Feel free to reopen if issue repeated, Thank you.
