### ISSUE TITLE
Unable to compile gradle: Failed to resolve

### ISSUE THREAD

**Issue by ag7775** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#38]
![screenshot 92](https://user-images.githubusercontent.com/22426105/36835794-5d892f8a-1d5d-11e8-82f5-693631b8f47c.png)

**Comment by enricocid** [comment]
in Your build.gradle (Project) add this inside allprojects:

allprojects {
    repositories {
        ...
        **maven { url "https://jitpack.io" }**
    }
}

**Comment by myinnos** [comment]
Thanks @enricocid
