### ISSUE TITLE
Failed to resolve: com.github.myinnos:Alphabet Index-Fast-Scroll-RecyclerView:1.0.94

### ISSUE THREAD

**Issue by AkashOpenxcell** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#48]
Not able to setup following dependance for AndroidX vesrion.
implementation 'com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.94'

**Comment by ghost** [comment]
me too

**Comment by odifek** [comment]
Any solution yet? Cannot resolve dependency

**Comment by dovahkrid** [comment]
there is no 1.0.94 version
https://jitpack.io/#com.github.myinnos/AlphabetIndex-Fast-Scroll-RecyclerView

**Comment by Geraldo-Neto** [comment]
Remember to add 

```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}

```
And just use the version 1.0.92. It works with AndroidX.

**Comment by myinnos** [comment]
Fixed and Released new version
Updated [READ.ME](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/blob/master/README.md)
[1.0.95](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/releases/tag/1.0.95)

Feel free to reopen if issue repeated, Thank you.
