### ISSUE TITLE
OnScroll AutoHide Feature

### ISSUE THREAD

**Issue by shaiban365** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#50]
Hi, It would be very helpful feature if we have autohide flag for automatically show scroller on scroll and hide when not scrolling. Thank you

Example:
https://github.com/timusus/RecyclerView-FastScroll

**Comment by AbandonedCart** [comment]
@cseshaiban https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/pull/82
