### ISSUE TITLE
java.lang.Object[] cannot be cast to java.lang.String[]

### ISSUE THREAD

**Issue by banyanstudio** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#52]
java.lang.Object[] cannot be cast to java.lang.String[]

 public void setAdapter(RecyclerView.Adapter adapter) {
        if (adapter instanceof SectionIndexer) {
            adapter.registerAdapterDataObserver(this);
            mIndexer = (SectionIndexer) adapter;
            mSections = (String[]) mIndexer.getSections(); <--- erro line(ava.lang.Object[] cannot be cast to java.lang.String[])
        }
    }

**Comment by banyanstudio** [comment]
Kindly use like this to convert object array to string Array
String[] stringArray = Arrays.copyOf(objectArray, objectArray.length, String[].class);

**Comment by banyanstudio** [comment]
Issue fixed To those who are using kotlin
Give array as mentioned below
at override fun getSections() method
alphabetsArrayList.toArray<String>(alphabetsArrayList.toTypedArray())

**Comment by savked** [comment]
For anyone still having the same bug on Kotlin, use:

`return sections.toTypedArray() as Array<Any>
`

for some reason only `return sections.toTypedArray()
` doesn't work.

**Comment by chitgoks** [comment]
I suggest this be included in the docs. if no one bothers to look at the closed issues, then they may not find out about this workaround.
