### ISSUE TITLE
not working in appCompect 

### ISSUE THREAD

**Issue by pateljigar7210** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#53]
mRecyclerView.setPreviewColor("#00FF00");
        mRecyclerView.setPreviewTextColor("#FFFFFF");
        mRecyclerView.setPreviewTransparentValue(0.6f);

@not working in appCompect

**Comment by myinnos** [comment]
Fixed and Released new version
Updated [READ.ME](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/blob/master/README.md)
[1.0.95](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/releases/tag/1.0.95)

Feel free to reopen if issue repeated, Thank you.
