### ISSUE TITLE
how can i give border only in alphabetic indexer

### ISSUE THREAD

**Issue by zadShaikh** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#55]
how can i give border only in alphabetic indexer
now want full background color only border color

**Comment by myinnos** [comment]
Added in new version 
Updated [READ.ME](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/blob/master/README.md)
[1.0.95](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/releases/tag/1.0.95)
