### ISSUE TITLE
How to scroll at specific section

### ISSUE THREAD

**Issue by avisingh736** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#58]
I want to scroll it to "F" section when it opens, Is it possible?
have tried with
`mAdapter?.let {
            it.getPositionForSection(6)
            it.notifyDataSetChanged()
        }`

`mAdapter?.let {
            it.getSectionForPosition(6)
            it.notifyDataSetChanged()
        }`

**Comment by myinnos** [comment]
you can use the below default method on Activity
`int mScrollPosition = 5;`
` Objects.requireNonNull(mRecyclerView.getLayoutManager()).scrollToPosition(mScrollPosition);`
