### ISSUE TITLE
Implementing the library

### ISSUE THREAD

**Issue by theoklink** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#59]
The following error occurs when trying to implement:
Could not find com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.94.
Searched in the following locations:
  - file:/C:/sdk/extras/m2repository/com/github/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/1.0.94/AlphabetIndex-Fast-Scroll-RecyclerView-1.0.94.pom
  - file:/C:/sdk/extras/m2repository/com/github/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/1.0.94/AlphabetIndex-Fast-Scroll-RecyclerView-1.0.94.jar
  - file:/C:/sdk/extras/google/m2repository/com/github/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/1.0.94/AlphabetIndex-Fast-Scroll-RecyclerView-1.0.94.pom
  - file:/C:/sdk/extras/google/m2repository/com/github/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/1.0.94/AlphabetIndex-Fast-Scroll-RecyclerView-1.0.94.jar
  - file:/C:/sdk/extras/android/m2repository/com/github/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/1.0.94/AlphabetIndex-Fast-Scroll-RecyclerView-1.0.94.pom
  - file:/C:/sdk/extras/android/m2repository/com/github/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/1.0.94/AlphabetIndex-Fast-Scroll-RecyclerView-1.0.94.jar
  - https://dl.google.com/dl/android/maven2/com/github/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/1.0.94/AlphabetIndex-Fast-Scroll-RecyclerView-1.0.94.pom
  - https://dl.google.com/dl/android/maven2/com/github/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/1.0.94/AlphabetIndex-Fast-Scroll-RecyclerView-1.0.94.jar
  - https://jcenter.bintray.com/com/github/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/1.0.94/AlphabetIndex-Fast-Scroll-RecyclerView-1.0.94.pom
  - https://jcenter.bintray.com/com/github/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/1.0.94/AlphabetIndex-Fast-Scroll-RecyclerView-1.0.94.jar

**Comment by ZaccharieBOUVY** [comment]
there is no 1.0.94 version
https://jitpack.io/#com.github.myinnos/AlphabetIndex-Fast-Scroll-RecyclerView

**Comment by theoklink** [comment]
In that case the detail on the main page is wrong:
    // AndroidX version
       implementation 'com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.94'

**Comment by theoklink** [comment]
The instructions given are just not working. Tried every version.
ERROR: Failed to resolve: com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.92

**Comment by Geraldo-Neto** [comment]
Remember to add 

```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}

```
And just use the version 1.0.92. It works with AndroidX.

**Comment by theoklink** [comment]
Repeated the process as described
1. my project build.gradle 
```
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public'}
        maven { url 'https://jitpack.io'}
    }
```
from the information provided in the 
in the module build.gradle
```
    implementation 'de.hdodenhof:circleimageview:3.0.0'
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
    implementation 'jp.wasabeef:recyclerview-animators:2.3.0'
    implementation 'com.iarcuschin:simpleratingbar:0.1.5'
    implementation 'com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.92'
```
as you can see  references to com.github etc exists which work fine
However, despite al this

ERROR: Failed to resolve: com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.91

I again tried each version available to no avail.
Android Studio 3.4.1

**Comment by theoklink** [comment]
Developer clearly lost interest in this. There is another issue onn the same subje t with the same reslonses but no resolution,
