### ISSUE TITLE
Failed to resolve library

### ISSUE THREAD

**Issue by abhishekinexture** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#60]
As per your description, I am integrating this library but I got following error.

This is my build.gradle(project) file:
`allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}`

build.gradel(app) file

`implementation 'com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.94'`

**ERROR: Failed to resolve: com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.94**

**Comment by marenovakovic** [comment]
Same

**Comment by myinnos** [comment]
Fixed and Released new version
Updated [READ.ME](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/blob/master/README.md)
[1.0.95](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/releases/tag/1.0.95)

Feel free to reopen if issue repeated, Thank you.
