### ISSUE TITLE
Indices on the right doesn't take into account clipToPadding

### ISSUE THREAD

**Issue by janbolat** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#75]
Hi!
Thank you for the library.
As it can be seen indices are drawn to the very bottom. But RecyclerView's content is not (it has padding set)

![image](https://user-images.githubusercontent.com/6511056/112720368-1218a180-8f28-11eb-9861-8b6a7a8ca202.png)

**Comment by AbandonedCart** [comment]
https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/pull/78

**Comment by myinnos** [comment]
https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/releases/tag/1.0.97
