### ISSUE TITLE
Can not set index bar fully transparent

### ISSUE THREAD

**Issue by xuanthupro** [myinnos/AlphabetIndex-Fast-Scroll-RecyclerView#8]
Hello,

I've tried many ways but can not set background of index bar transparent.
I've used:
recyclerView.setIndexBarTransparentValue((float) 0);
recyclerView.setIndexBarColor("#00FFFFFF");
and tried to set it using xml too, but no luck.

Can you help me?
Thanks.

**Comment by myinnos** [comment]
Always set solid color to IndexBarColor
`recyclerView.setIndexBarColor("#FFFFFF");`

Then change IndexBarTransparentValue as you need;
example 1:
`recyclerView.setIndexBarTransparentValue((float) 4);`
example 2:
`recyclerView.setIndexBarTransparentValue((float) 1);`

**Comment by xuanthupro** [comment]
Hi @myinnos ,
I've found the reason for this issue.
Your newest code which able to set transparent color is not available on version 1.0.2 yet.
So that the method setIndexBarTransparentValue doesn't work as expected

Can you update it soon?
Thanks

**Comment by myinnos** [comment]
`setIndexBarTransparentValue` available on 1.0.2 , please fork the repo and check example once!

**Comment by xuanthupro** [comment]
Yes, it's available but doesn't work correctly.
On initialized, its value is always set as 150 (default value). After screen orientation, new value is appied.

**Comment by myinnos** [comment]
Yup! found it! its occurring on screen rotation

**Comment by jonas-app** [comment]
@xuanthupro @myinnos 
I had the same issue and fixed it with https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/pull/5.
The code is already merged but there is no new release.
@myinnos Can you please create a new release, I am also missing the typeface feature I added (this is also already merged).

**Comment by myinnos** [comment]
@jonas-arkulpa sorry for the delay! 
Released new version [1.0.3](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/releases/tag/1.0.3)

Let me know whether this issues is resolved or not ?

**Comment by jonas-app** [comment]
@myinnos Thanks for the release.
The transparency feature is working as expected.
But I'm not sure about the screen rotation problem you talked above.
I never had an issue with screen rotations.

**Comment by myinnos** [comment]
@jonas-arkulpa thats cool!

@xuanthupro we need some help from you to resolve this bug! Please compare your code to [this](https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView/tree/master/app/src/main) example.

**Comment by xuanthupro** [comment]
Hello @myinnos 
The transparency feature works well when you releases new version.
You don't need to change anything in implementation code.
Thanks

**Comment by myinnos** [comment]
@xuanthupro great to here from you :) happy coding
